name: Tests

on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and test
      run: |
        xcodebuild test -scheme Beaverlist -destination 'platform=iOS Simulator,name=iPhone 13 Pro Max,OS=16.2'
